### ISSUE TITLE
Smooth loss is 0.0000 when Training with one GPU

### ISSUE THREAD

**Issue by SkeletonOne** [yinghdb/EmbedMask#6]
With one 1080Ti, I tried to train embedmask R50. The config was altered to 
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (240000, 320000)
  MAX_ITER: 360000
  IMS_PER_BATCH: 4
However, smooth loss is 0.0000 based on this settings. How to solve it?
2019-12-30 12:47:34,145 fcos_core.trainer INFO: eta: 3 days, 18:35:54  iter: 20  loss: 3.3032 (3.4775)  loss_cls: 1.0743 (1.0808)  loss_reg: 0.9765 (0.9732)  loss_centerness: 0.6795 (0.6856)  mask_loss: 0.5730 (0.7380)  smooth_loss: 0.0000 (0.0000)  time: 0.8129 (0.9060)  data: 0.0085 (0.0548)  lr: 0.000833  max mem: 6907

**Comment by yinghdb** [comment]
It is normal that the smooth loss is very close to 0.0 at first. That is because at first, the box prediction is very inaccurate. and according to the sampling strategy for embedding and margin prediction, only samples with good box predictions are used to compute mask loss and smooth loss (named positive samples for embedding and margin). When all samples for the object can not produce good box predictions, we pick the sample with the best box prediction as the only positive sample, therefore the smooth loss in that object is equal to 0. So, you do not need to worry about that.

**Comment by SkeletonOne** [comment]
@yinghdb Thanks for your reply. I will try training it for a longer time and see the results.
